- hosts: terraform-ansible
  tasks:
  - name: criando o arquivo index.html
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Vai lรก Saraiva</h1>
  - name: criando o servidor
    shell: "nohup busybox httpd -f -p 8080 &"